#!/bin/bash

pip3 install setuptools -U
pip3 install tqdm unidecode numpy scipy tensorflow pyldavis
pip3 install sklearn_crfsuite sklearn scikit-learn requests rapidfuzz
pip3 install pandas toolz
pip3 install PySastrawi matplotlib seaborn networkx
python3 setup.py install
