WANDB_PROJECT="dpo-malaysian-mistral-7b-32k-instructions-v4" \
torchrun --nproc_per_node 8 \
-m dpo \
--model_name_or_path=mesolitica/malaysian-mistral-7b-32k-instructions-v4 \
--per_device_train_batch_size 4 \
--gradient_accumulation_steps 2 \
--learning_rate 5e-6 \
--warmup_ratio 0.1 \
--bf16 \
--do_train \
--do_eval false \
--num_train_epochs 10 \
--logging_steps 1 \
--save_steps 50 \
--save_total_limit 3 \
--gradient_checkpointing true \
--output_dir="dpo-mistral" \
--max_length 8192 \
--max_prompt_length 1024 \
--log_level "info" \
--torch_dtype "bfloat16"