rules_normalizer = {
    'yeh': 'yeah',
    'yeaah': 'yeah',
    'yea': 'you',
    'lol': 'laughing out loud',
    'lolll': 'laughing out loud',
    'lolol': 'laughing out loud',
    'loll': 'laughing out loud',
    'lool': 'laughing out loud',
    'lollol': 'laughing out loud',
    'kok': 'laughing out loud',
    'im': 'i',
    'i': 'iphone',
    'am': "i'm",
    'iml': "i'm",
    'poppin': 'popping',
    'speakin': 'speaking',
    'b': 'by',
    'cuz': 'because',
    'cause': 'because',
    'casue': 'because',
    'becos': 'because',
    'bc': 'because',
    'cus': 'because',
    'beacause': 'because',
    'cuzz': 'because',
    'couse': 'because',
    'xause': 'because',
    'bcos': 'because',
    'becase': 'because',
    'diid': 'did',
    'u': 'your',
    'yo': 'your',
    'yooo': 'you',
    'y': 'why',
    'yu': 'your',
    'yew': 'you',
    'uuu': 'you',
    'gyu': 'you',
    'ya': 'yourself',
    'yuuh': 'you',
    'youu': 'you',
    'yoi': 'you',
    'uon': "you won't",
    'youuu': 'you',
    'yoo': 'you',
    'ui': 'you',
    'lmao': 'laughing my ass off',
    'lmaoo': 'laughing my ass off',
    'lmaooo': 'laughing my ass off',
    'mins': 'minutes',
    'min': 'minutes',
    'okk': 'okay',
    'okee': 'okay',
    'okeh': 'okay',
    'okc': 'okay',
    'lmfao': 'laughing my fucking ass off',
    'lmfaoo': 'laughing my fucking ass off',
    'lmfaooo': 'laughing my fucking ass off',
    'lmfaooooo': 'laughing my fucking ass off',
    'feela': 'feels',
    'thisnewssoccer': 'this news soccer',
    'r': 'rest',
    'doin': 'doing',
    'fucken': 'fucking',
    'fakin': 'fucking',
    'fuckn': 'fucking',
    'frickin': 'fucking',
    'fuckin': 'fucking',
    'fkn': 'fucking',
    'fckn': 'fucking',
    'fckng': 'fucking',
    'fuccin': 'fucking',
    'faking': 'fucking',
    'pls': 'please',
    'plz': 'please',
    'pleaseee': 'please',
    'pleeze': 'please',
    'pleasee': 'please',
    'idek': "i don't even know",
    'smh': 'shaking my head',
    'smhh': 'shaking my head',
    'wassup': "what's up",
    'convo': 'conversation',
    'soooooo': 'so',
    'soo': 'so',
    'sooo': 'so',
    'soooo': 'so',
    'aint': "ain't",
    'nt': "ain't",
    'cant': "can't",
    'cnt': "can't",
    'havin': 'having',
    'hving': 'having',
    'drove': 'driven',
    'idk': "i don't know",
    'ain': 'am',
    'bee': 'am',
    'msges': 'massages',
    'hw': 'how',
    'sopposed': 'supposed',
    'tryin': 'trying',
    'everyones': "everyone's",
    'eps': 'especially',
    'esp': 'especially',
    'wtf': 'what the fuck',
    'finna': 'going to',
    'outtie': 'going to',
    'layghing': 'laughing',
    'ttc': 'text to cell',
    'gunna': 'gonna',
    'gon': 'gonna',
    'gona': 'gonna',
    'gna': 'gonna',
    'ima': "i'm going to",
    'imma': "i'm going to",
    'dont': "don't",
    'font': "don't",
    'dnt': "doesn't",
    'dun': 'done',
    "do'nt": "don't",
    'wouldnt': "wouldn't",
    'follback': 'follow back',
    'followback': 'follow back',
    'bros': 'brothers',
    'brothas': 'brothers',
    'probs': 'problems',
    'prolly': 'probably',
    'prob': 'problem',
    'ik': 'i know',
    'thats': "that's",
    'dats': "that's",
    'tes': "that's",
    'feelin': 'feeling',
    'woulda': 'would have',
    'wouldve': 'would have',
    'outta': 'out of',
    'bmore': 'be more',
    'fck': 'fuck',
    'fak': 'fuck',
    'f': 'fuck',
    'fuh': 'fuck',
    'fuuck': 'fuck',
    'fucc': 'fuck',
    'fuc': 'fuck',
    'fuq': 'fuck',
    'fcuk': 'fuck',
    'goin': 'going',
    'goxung': 'going',
    'nigga': 'nigger',
    'nggr': 'nigger',
    'niggaz': 'niggers',
    'nikkar': 'nigger',
    'nigguh': 'nigger',
    'niggah': 'nigger',
    'niggas': 'niggers',
    'nig': 'nigger',
    'niigga': 'nigger',
    'doesnt': "doesn't",
    'dosent': "doesn't",
    'omg': 'oh my god',
    'omaigod': 'oh my god',
    'ntmy': 'nice to meet you',
    'btw': 'by the way',
    'ur': 'your',
    'youre': "you're",
    'lil': 'little',
    'likkle': 'little',
    'you': 'your',
    'timeee': 'time',
    'tim': 'time',
    'tme': 'time',
    'spors': 'sports',
    'dat': 'the',
    'tjat': 'that',
    'tht': 'that',
    'tgat': 'that',
    'datz': 'that',
    'folower': 'follower',
    'colour': 'color',
    'wut': 'what',
    'whta': 'what',
    'wat': 'what',
    'wah': 'what',
    'wha': 'what',
    'whut': 'what',
    'bru': 'brother',
    'bruh': 'brother',
    'bro': 'brother',
    'brohh': 'brother',
    'brotherr': 'brother',
    'broo': 'brother',
    's': 'is',
    'das': 'is',
    'iss': 'is',
    'to': 'the',
    'tha': 'the',
    'd': 'the',
    'da': 'the',
    'teh': 'the',
    'duh': 'the',
    'der': 'the',
    'who': "who's",
    'whos': "who's",
    'whois': "who's",
    'baby': 'babysit',
    'tho': 'though',
    'thou': 'though',
    'cab': 'can',
    'cn': 'can',
    'ca': 'can',
    'favaroite': 'favorite',
    'favourite': 'favorite',
    'fav': 'favor',
    'iight': 'alright',
    'alrightt': 'alright',
    'aight': 'alright',
    'iiiiight': 'alright',
    'ight': 'alright',
    'chill': 'child',
    'nd': 'and',
    'n': 'in',
    'aaand': 'and',
    'e': 'and',
    'hmu': 'hit me up',
    'boi': 'boy',
    'gettin': 'getting',
    'bavk': 'back',
    'bk': 'back',
    'bacc': 'back',
    'bck': 'back',
    'bac': 'back',
    'workin': 'working',
    'asf': 'as fuck',
    'af': 'as fuck',
    'takin': 'taking',
    'tf': 'the fuck',
    'nahh': 'no',
    'noa': 'no',
    'naw': 'now',
    'nah': 'now',
    'ig': 'instagram',
    'insta': 'instagram',
    'ill': "i'll",
    'bff': 'best friends forever',
    'evryboddy': 'everybody',
    'asap': 'as soon as possible',
    'whats': "what's",
    'liek': 'like',
    'lyk': 'like',
    'likee': 'like',
    'lik': 'like',
    'yaaaas': 'yes',
    'yesssssss': 'yes',
    'yess': 'yes',
    'yas': 'yes',
    'yesss': 'yes',
    'com': 'come',
    'cum': 'come',
    'comeee': 'come',
    'somethin': 'something',
    'smth': 'something',
    'sumtin': 'something',
    'donut': 'doughnut',
    'na': 'not',
    'noooo': 'not',
    'notttt': 'not',
    'thankyou': 'thank you',
    'ikr': 'i know right',
    'girlz': 'girls',
    'oomf': 'one of my followers',
    'ily': 'i love you',
    'runnin': 'running',
    'beutiful': 'beautiful',
    'ws': 'was',
    'vry': 'very',
    'v': 'versus',
    'earnng': 'earning',
    'rt': 'retweet',
    'mbf': 'must be following',
    'pmsl': 'pissing myself laughing',
    'hommie': 'homie',
    'slackin': 'slacking',
    'omw': 'on my way',
    'outtahere': 'out there',
    'jfb': 'jesus fucking bale',
    'heare': 'here',
    'heree': 'here',
    'prayin': 'praying',
    'bday': 'birthday',
    'birthdayyyyy': 'birthday',
    'bout': 'about',
    'bwt': 'about',
    'abt': 'about',
    'abwt': 'about',
    'havent': "haven't",
    'havnt': "haven't",
    'gota': 'gotta',
    'gottta': 'gotta',
    'yall': "y'all",
    'yal': "y'all",
    'hwk': 'homework',
    'omfg': 'oh my fucking god',
    'p': 'pm',
    'wen': 'when',
    'c': 'see',
    'cee': 'see',
    'comin': 'coming',
    'comeing': 'coming',
    'cumin': 'coming',
    'commin': 'coming',
    'smokin': 'smoking',
    'nothin': 'nothing',
    'nunthing': 'nothing',
    'nowt': 'nothing',
    'nun': 'nothing',
    'gf': 'girlfriend',
    'girlfrnd': 'girlfriend',
    'hasnt': "hasn't",
    'ds': 'this',
    'dis': 'this',
    'diss': 'disrespect',
    'tiz': 'this',
    'dept': 'department',
    'ttatt': 'the truth about the truth',
    'niggss': 'niggers',
    'theyre': "they're",
    'pic': 'picture',
    'favour': 'favor',
    'jk': 'just kidding',
    'busses': 'buses',
    'wit': 'with',
    'wid': 'with',
    'wif': 'with',
    'w': 'with',
    'lovin': 'loving',
    'dm': 'direct message',
    'guyz': 'guys',
    'congrats': 'congratulations',
    'congra': 'congratulations',
    'congrates': 'congratulations',
    'lmk': 'let me know',
    'childrens': 'children',
    'chillll': 'chill',
    'decor': 'decoration',
    'fb': 'facebook',
    'bbm': 'blackberry messenger',
    'goood': 'good',
    'gudd': 'good',
    'gud': 'good',
    'cutee': 'cute',
    'cuteee': 'cute',
    '2night': 'tonight',
    'tonite': 'tonight',
    '2moro': 'tomorrow',
    'tomorroww': 'tomorrow',
    'tmr': 'tomorrow',
    'tmmrow': 'tomorrow',
    'kno': 'know',
    'knw': 'know',
    'onow': 'know',
    'pple': 'people',
    'ppl': 'people',
    'pepole': 'people',
    'thot': 'thought',
    'acc': 'account',
    'evrry': 'every',
    'tbh': 'to be honest',
    'flexin': 'flexing',
    'waitin': 'waiting',
    'hav': 'have',
    'hdve': 'have',
    'av': 'avenue',
    've': 'have',
    'hve': 'have',
    'hv': 'have',
    'moist': 'most',
    'makig': 'making',
    'makin': 'making',
    'makinng': 'making',
    'm': 'millions',
    'idgaf': "i don't give a fuck",
    'ive': "i've",
    'lukkk': 'look',
    'eva': 'ever',
    'gt': 'get',
    'getta': 'get',
    'yt': 'yet',
    'thx': 'thanks',
    'thanx': 'thanks',
    'thnx': 'thanks',
    'dw': "don't worry",
    'fosure': 'for sure',
    'idc': "i don't care",
    '2': 'too',
    'ro': 'to',
    'ko': 'to',
    'tooo': 'too',
    'o': 'oh',
    'smilin': 'smiling',
    'disappearin': 'disappearing',
    'bouta': 'about to',
    'boutta': 'about to',
    'ofcourse': 'of course',
    'weddn': 'wedding',
    'analyzin': 'analyzing',
    'em': 'them',
    'dem': 'them',
    'demam': 'them',
    'justunfollow': 'just unfollow',
    'fw': 'forward',
    'ashell': 'as hell',
    'ctfu': 'cracking the fuck up',
    'grt': 'great',
    'yolo': 'you only live once',
    'ohmygosh': 'oh my gosh',
    'pblm': 'problem',
    'bby': 'baby',
    'babyy': 'baby',
    'cherr': 'cherry',
    'its': "it's",
    'rn': 'right now',
    'tweetin': 'tweeting',
    'wks': 'weeks',
    'portlan': 'portland',
    'yaayyy': 'yay',
    'fren': 'friend',
    'frnd': 'friend',
    'llls': 'laughing like shit',
    'lls': 'laughing like shit',
    'fangirl': 'fan girl',
    'itd': "it'd",
    'pompo': 'pompous',
    'arent': "aren't",
    'tlkin': 'talking',
    'talkin': 'talking',
    'btch': 'bitch',
    'sorrynotsorry': 'sorry not sorry',
    'oit': 'on',
    'thaaaaaaaaank': 'thank',
    'tnk': 'thank',
    'thaaank': 'thank',
    'happppy': 'happy',
    'hapi': 'happy',
    'labl': 'label',
    'nvm': 'never mind',
    'forreal': 'for real',
    'fr': 'for real',
    'foreal': 'for real',
    'moms': "mom's",
    'friends': "friend's",
    'a': 'i',
    'grp': 'group',
    'realise': 'realize',
    'labour': 'labor',
    'mum': 'mom',
    'telly': 'television',
    'sado': 'sad',
    'odawise': 'otherwise',
    'chs': 'cheese',
    'ltu': 'lithuania',
    'potatoe': 'potato',
    'potata': 'potato',
    'fingre': 'finger',
    'penus': 'pennis',
    'xant': 'want',
    'dyed': 'dried',
    'facee': 'face',
    'betta': 'better',
    'bettr': 'better',
    'thang': 'thing',
    'tix': 'tickets',
    'gurl': 'girl',
    'girllll': 'girl',
    'sayin': 'saying',
    'bein': 'being',
    'dikes': 'dislikes',
    'wimme': 'with me',
    'growthzawya': 'growth zawya',
    'registra': 'registration',
    'redsox': 'red sox',
    'mlb': 'major league baseball',
    'rpg': 'role playing game',
    'spinoff': 'spin off',
    'tellin': 'telling',
    'paradice': 'paradise',
    'futbol': 'football',
    'worksop': 'workshop',
    'playin': 'playing',
    'ilysm': 'i love you so much',
    'missin': 'missing',
    'ftw': 'for the win',
    'wont': "won't",
    'won': "won't",
    'tfios': 'the fault in our stars',
    "could've": 'could have',
    'coulda': 'could have',
    'cuttin': 'cutting',
    'gtfo': 'get the fuck out',
    'jst': 'just',
    'juss': 'just',
    'jus': 'just',
    'ja': 'just',
    'thinkin': 'thinking',
    'werent': "weren't",
    'fml': 'fuck my life',
    'wondrful': 'wonderful',
    '4': 'for',
    'anykind': 'any kind',
    'parkd': 'parked',
    'dan': 'than',
    'omm': 'on my mom',
    'ion': "i don't",
    'giva': 'give a',
    'lyft': 'lift',
    'finalise': 'finalize',
    'locced': 'locked',
    'imu': 'i miss you',
    'folkz': 'folks',
    'liv': 'live',
    'companyy': 'company',
    'laterr': 'later',
    'maybee': 'may be',
    'myb': 'may be',
    'lawd': 'lord',
    'wth': 'what the hell',
    'onwards': 'onward',
    'thru': 'through',
    'makeout': 'make out',
    'sangin': 'singing',
    'singin': 'singing',
    'yessir': 'yes sir',
    'fwy': 'fucking with you',
    'puttin': 'putting',
    'ma': 'my',
    'noms': 'nominations',
    'autocorrect': 'auto correct',
    'birches': 'bitches',
    'bitchessssss': 'bitches',
    'bitchs': 'bitches',
    'urself': 'yourself',
    'hof': 'hall of fame',
    'didn': "didn't",
    'didnt': "didn't",
    'ithink': 'i think',
    'sht': 'shit',
    'shxt': 'shit',
    'dere': 'dare',
    'screamin': 'screaming',
    'wasnt': "wasn't",
    'thers': "there's",
    'theres': "there's",
    'buss': 'bust',
    'seriusly': 'seriously',
    'hes': "he's",
    'jord': 'joke',
    'shoutout': 'shout out',
    'swthat': 'shout out',
    'hbd': 'happy birthday',
    'unnerstand': 'understand',
    'vid': 'video',
    'hurtin': 'hurting',
    'upp': 'up',
    '2d': 'today',
    'stfu': 'shut the fuck up',
    'goodluck': 'good luck',
    'kissy': 'kissing',
    'hottttt': 'hot',
    'tryna': 'trying to',
    'trynna': 'trying to',
    'sittin': 'sitting',
    'chewin': 'chewing',
    'wherr': 'where',
    'judgement': 'judgment',
    'limites': 'limits',
    'shouldnt': "shouldn't",
    'textin': 'texting',
    'rip': 'rest in peace',
    'weeknd': 'weekend',
    'wkend': 'weekend',
    'wknd': 'weekend',
    'coolin': 'cooling',
    'fone': 'phone',
    'phonee': 'phone',
    'rhe': 'her',
    'hella': 'hell of a lot of',
    'og': 'oh god',
    'whatevahh': 'whatever',
    'wateva': 'whatever',
    'wayy': 'way',
    'afta': 'after',
    'aftr': 'after',
    'couldnt': "couldn't",
    'chillen': 'chilling',
    'chillin': 'chilling',
    'chilln': 'chilling',
    'thottin': 'thotting',
    'byyeee': 'bye',
    'smbdy': 'somebody',
    'absolut': 'absolute',
    'transforma': 'transformation',
    'cllrs': 'circulars',
    'watchin': 'watching',
    'leavin': 'leaving',
    'onlne': 'online',
    'yknow': 'you know',
    'considerin': 'considering',
    'payin': 'paying',
    'theyd': 'they had',
    'thnk': 'think',
    'waka': 'wanna',
    'wana': 'wanna',
    'wearin': 'wearing',
    'mayne': 'mine',
    'rockin': 'rocking',
    'cmon': 'come on',
    'cuss': 'curse',
    'awesom': 'awesome',
    'keepin': 'keeping',
    'tollfree': 'toll free',
    'wer': 'were',
    'peoples': "people's",
    'addrsd': 'addressed',
    'sled': 'slide',
    'mountains': 'mountain',
    'puddin': 'pudding',
    'urg': 'urgent',
    'busi': 'business',
    'pissin': 'pissing',
    'settin': 'setting',
    'klick': 'click',
    'shite': 'shitty',
    'info': 'information',
    'neva': 'never',
    'nvr': 'never',
    'oneee': 'one',
    'alll': 'all',
    'twiter': 'twitter',
    'frontin': 'fronting',
    'motha': 'mother',
    'mutha': 'mother',
    'fucka': 'fucker',
    'championssssss': 'champions',
    'luv': 'love',
    'seris': 'series',
    'bfor': 'before',
    'b4': 'before',
    'kiddibg': 'kidding',
    'blarin': 'blaring',
    'but': 'butt',
    'gotdamn': 'god damn',
    'fomd': 'from',
    'smfd': 'suck my fucking dick',
    'ttyl': 'talk to you later',
    'sidechicks': 'side chicks',
    'cuh': 'see you',
    'gayz': 'gays',
    'clownin': 'clowning',
    'imo': 'in my opinion',
    'lfc': 'liverpool football club',
    'lastnight': 'last night',
    'momma': 'mama',
    'rly': 'really',
    'talm': 'tell them',
    'whs': 'what he said',
    'wrkd': 'worked',
    'wrked': 'worked',
    'presh': 'precious',
    'hallo': 'hello',
    'livin': 'living',
    'masturbatin': 'masturbating',
    'jumpin': 'jumping',
    'fri': 'friday',
    'kidnapp': 'kidnap',
    'hoes': 'whores',
    'lightskinned': 'light skinned',
    'stuckup': 'stuck up',
    'hk': 'hong kong',
    'calld': 'called',
    'wildin': 'wilding',
    'ffs': "for fuck's sake",
    'friggen': 'freaking',
    'freakin': 'freaking',
    'theatre': 'theater',
    'bestfriends': 'best friends',
    'coool': 'cool',
    'shuold': 'should',
    'frfr': 'for real for real',
    'colections': 'collections',
    'om': 'oh my',
    'g': 'god',
    'goddd': 'god',
    'ourside': 'our side',
    'lml': 'love my life',
    'sellin': 'selling',
    'rts': 'retweets',
    'youve': "you've",
    'alot': 'a lot',
    'alots': 'a lot',
    'whol': 'whole',
    'malcom': 'malcolm',
    'tftf': 'thanks for the follow',
    'gby': 'god bless you',
    'appt': 'appointment',
    'ftfy': 'fixed that for you',
    'programme': 'program',
    'winn': 'win',
    'peterpan': 'peter pan',
    'favs': 'favors',
    'flavour': 'flavor',
    'nowplaying': 'now playing',
    'mfs': 'mother fuckers',
    'songz': 'songs',
    'lightskin': 'light skin',
    'highkey': 'high key',
    'homo': 'homosexual',
    'fuxked': 'fucked',
    'travellers': 'travelers',
    '14million': '14 million',
    'premierleague': 'premier league',
    'albo': 'albanian',
    'mf': 'mother fucker',
    'whatchu': 'what you',
    'bestfriend': 'best friend',
    'bestie': 'best friend',
    'secs': 'seconds',
    'ridin': 'riding',
    'travelling': 'traveling',
    'luvely': 'lovely',
    'xfactor': 'x factor',
    'wrks': 'works',
    'cuase': 'cause',
    'olny': 'only',
    'judgemental': 'judgmental',
    'rekon': 'reckon',
    'friendswithyou': 'friends with you',
    'welkam': 'welcome',
    'cryin': 'crying',
    'cryigm': 'crying',
    'millionbiafrans': 'million biafrans',
    'britishgovt': 'british government',
    'lysm': 'love you so much',
    'clappin': 'clapping',
    'tl': 'timeline',
    'skillz': 'skills',
    'alon': 'alone',
    'gtf': 'get to fuck',
    'initia': 'initial',
    'shoulda': 'should have',
    'shouldve': 'should have',
    'incase': 'in case',
    'fotos': 'photos',
    'sumwhere': 'somewhere',
    'woah': 'wow',
    'iwonder': 'i wonder',
    'sum': 'some',
    'theirselves': 'themselves',
    'gingerale': 'ginger ale',
    'todays': "today's",
    'irl': 'in real life',
    'waifu': 'wife',
    'crushcrushcrush': 'crush',
    'ou': 'our',
    'ads': 'advertisements',
    'jpanese': 'japanese',
    'inspite': 'in spite',
    'msg': 'message',
    'utlisation': 'utilization',
    'turnin': 'turning',
    'eachother': 'each other',
    'avg': 'average',
    'wyd': 'what you doing',
    'chainz': 'chains',
    'godbless': 'god bless',
    'infactuated': 'infatuated',
    'socal': 'social',
    'taek': 'take',
    'tak': 'take',
    'atractive': 'attractive',
    'buuut': 'but',
    'bt': 'but',
    'def': 'definitely',
    'dey': 'they',
    'husbnd': 'husband',
    'sads': 'sadness',
    'fanfic': 'fan fiction',
    'startin': 'starting',
    'musik': 'music',
    'japane': 'japan',
    'leakd': 'leaked',
    'fwm': 'fuck with me',
    'perfomance': 'performance',
    'thankin': 'thanking',
    'arres': 'arrest',
    'thotful': 'thoughtful',
    'madris': 'madrid',
    'schedual': 'schedule',
    'sat': 'saturday',
    'rumours': 'rumors',
    'twitt': 'tweet',
    'mooooneeeeey': 'money',
    'hangin': 'hanging',
    'arse': 'arise',
    'clit': 'clitoris',
    'bf': 'boyfriend',
    'sundai': 'sunday',
    'pics': 'pictures',
    'awk': 'awkward',
    'asz': 'ass',
    'asss': 'ass',
    'spelt': 'spelled',
    'gotchu': 'got you',
    '2brwngrls': '2 brown girls',
    'tatts': 'tattoos',
    'lieing': 'lying',
    'realised': 'realized',
    'skys': 'sky',
    'friendzones': 'friend zones',
    'k': 'ok',
    'erly': 'early',
    'mrng': 'morning',
    'prayrs': 'prayers',
    'wry': 'worry',
    'meth': 'methamphetamine',
    'shakin': 'shaking',
    'ploting': 'plotting',
    'dunno': "don't know",
    'tradin': 'trading',
    'intox': 'intoxicate',
    'comeback': 'come back',
    'switchin': 'switching',
    'cataracs': 'cataracts',
    'sighh': 'sigh',
    'rumoured': 'rumored',
    'fanx': 'fans',
    'smel': 'smell',
    'owt': 'out',
    'giveaway': 'give away',
    'shittin': 'shitting',
    'whataburger': 'what a burger',
    'trippin': 'tripping',
    'highschool': 'high school',
    'mommas': "mama's",
    'pressurised2': 'pressurized to',
    'smileeeeee': 'smile',
    'openning': 'openings',
    'shuttup': 'shut up',
    'blackhawks': 'black hawks',
    'j': 'jay',
    'inna': 'in a',
    'ona': 'on a',
    'finnally': 'finally',
    '3weeks': '3 weeks',
    'askin': 'asking',
    'loveteam': 'love team',
    'layup': 'lay up',
    'now': 'nowadays',
    'geocities': 'geo cities',
    'getcha': 'get you',
    'donuts': 'doughnuts',
    'defendin': 'defending',
    'homeee': 'home',
    'brklyn': 'brooklyn',
    'brdg': 'bridge',
    'ln': 'lane',
    'blkd': 'blocked',
    'deadass': 'dead ass',
    'isnt': "isn't",
    'istening': 'listening',
    'sexe': 'sexy',
    'kissimmee': 'kiss me',
    'butthole': 'butt hole',
    'sogood': 'so good',
    'bsidez': 'besides',
    'boyz': 'boys',
}
