WANDB_PROJECT=mistral-474M-v2 \
torchrun --nproc_per_node 8 \
-m run_clm_mosaic \
--tokenizer_name malaysia-ai/bpe-tokenizer \
--model_name_or_path malaysian-mistral-474M-4096 \
--per_device_train_batch_size 34 \
--gradient_accumulation_steps 1 \
--output_dir pretrain-mistral-474M \
--bf16 \
--torch_dtype "bfloat16" \
--do_train \
--do_eval false \
--num_train_epochs 10 \
--train_file "mosaic-small-clm" \
--logging_steps 1 \
--learning_rate 2e-4 \
--weight_decay 1e-1 \
--block_size 4096 \
--save_steps 200 \
--save_total_limit 3 \
--gradient_checkpointing true